version: '3'
services:
  browserless:
    image: browserless/chrome:latest
    environment:
      # - DEBUG=browserless:*
      - MAX_CONCURRENT_SESSIONS=10
      - CONNECTION_TIMEOUT=60000
      - MAX_QUEUE_LENGTH=20
      - PREBOOT_CHROME=true
      - KEEP_ALIVE=true
      - CHROME_REFRESH_TIME=3600000
      - DEMO_MODE=false
      - HOST=0.0.0.0
      # - ENABLE_DEBUGGER=false
      - PORT=3000
      - WORKSPACE_DELETE_EXPIRED=true
    container_name: "browserless"
    ports:
      - "3030:3000"